allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
overrides:
  baseline-browser-mapping: 2.11.27
  browserslist: 4.29.3
  postcss: 8.5.28
  "@xmldom/xmldom": 0.8.13
  sharp: 0.35.5
  source-map-js: 1.2.2
